apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment-portal-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/0xNadr/environment-portal.git
    targetRevision: main
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: environment-portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
